rspec-tutorial-practise/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'students#index'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions'
  }
  resources :students

end

rspec-tutorial-practise/app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :student_skills, dependent: :destroy
  has_many :skills, through: :student_skills

  has_many :student_courses, dependent: :destroy
  has_many :courses, through: :student_courses

  # validates  :birthdate, :contact_no, :city, :state, :country, presence: true
  #  validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :email, uniqueness: true , presence: true
  # validates :contact_no,  uniqueness: true, length: { is: 10 }, presence: true
  # validates :password, confirmation: true,  presence: true
  validate :validate_country

  before_save :check_state_present

  def check_state_present
    self.state = country if state.nil?
  end

  def country_name
    country = IsoCountryCodes.find(self.country)
    country.name
  end

  def validate_country
    return if country.nil?

    return if Student.country_code_list.include?(country)

    errors.add(:country, 'is not valid')
  end

  def self.country_code_list
    IsoCountryCodes.all.map(&:alpha2)
  end

  def full_name
    "#{first_name} #{last_name}".strip
  end
end

rspec-tutorial-practise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_student!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birthdate, :contact_no, :city, :state, :country])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :birthdate, :contact_no, :city, :state, :country])
  end
end

rspec-tutorial-practise/app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |student|
      # StudentMailer.welcome_email(student).deliver_now
      # WelcomeEmailJob.perform_later(student.id)
      WelcomeEmailWorker.perform_async(student.id)
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

rspec-tutorial-practise/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!
  before_action :set_student, only: %i[show edit update destroy]
  before_action :prepare_devise_view, only: %i[new create edit update]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  # def create
  #   @student = Student.new(student_params)
  #   if @student.save
  #     flash[:notice] = 'Student was successfully created.'
  #     # redirect_to students_path
  #     # Redirects to the show page of the newly created student

  #     redirect_to @student
  #     # Render the index template instead of redirecting
  #     # render :index
  #   else
  #     # Renders new form if create fails
  #     render 'devise/registrations/new', status: :unprocessable_entity
  #   end
  # end

  def show; end

  def edit; 
  end

  def update
    if @student.update(student_update_params)
      flash[:notice] = 'Student was successfully updated'
      # redirect the index page
      redirect_to students_path
      # redirect_to @student
    else
      # Renders edit form if update rails
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @student = Student.find(params[:id])
    if @student.destroy
      flash[:notice] = "Student was successfully deleted"
      redirect_to students_path
    else
      flash[:alert] = 'There was an error deleting the student.'
      redirect_to students_path
    end
  end


  def upload_csv
    if params[:csv_file].present?
      CsvUploadWorker.perform_async(params[:csv_file].path)
      flash[:notice] = "CSV file uploaded. Students will be processed in the background."
    else
      flash[:alert] = "Please upload a CSV file."
    end
    redirect_to students_path
  end

  private

  def prepare_devise_view
    @resource = @student || Student.new
    @resource_name = :student
    @devise_mapping = Devise.mappings[:student]
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :password, :password_confirmation, :birthdate,
                                    :contact_no, :city, :state, :country)
  end

  def student_update_params
    params.require(:student).permit(:first_name, :last_name, :birthdate,  :city, :state, :country)
  end
end

rspec-tutorial-practise/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <% if Rails.env.test? %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', 'data-turbo': 'false' %>
  <% else %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
  <% end %>

  
  
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

rspec-tutorial-practise/app/views/reports/new.html.erb
<!-- app/views/reports/new.html.erb -->
<h1>New Report</h1>
<%= form_with model: @report do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit "Create Report" %>
  </div>
<% end %>

rspec-tutorial-practise/app/views/students/index.html.erb
  <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
  <% elsif alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <div class="container mt-5">
      <% if student_signed_in? %>
        <div class="alert alert-info text-center d-flex align-items-center justify-content-between" role="alert">
          <p class="mb-0">Logged in as: <strong><%= current_student.email %></strong></p>
            <%= button_to "Logout", destroy_student_session_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' }, class: 'btn btn-danger btn-md' %>
        </div>
      <% else %>
        <div class="alert alert-warning text-center" role="alert">
          <p class="mb-0">You are not logged in. Please log in or sign up to continue.</p>
        </div>
      <% end %>
    
      <h1 class="text-center mb-4 display-7">Listing All Students</h1>
    <table class="table table-bordered students" , id="students">
      <thead class="text-center">
        <tr>
          <th scope="col">First_Name</th>
          <th scope="col">Email</th>
          <th scope="col">Birth Date</th>
          <th scope="col">Contact No</th>
          <th scope="col">Address</th>
          <th scope="col" colspan="3">Actions</th>
        </tr>
      </thead>

      <div claas="card-deck">
        <tbody class="text-center">
          <% @students.each do |student| %>
            <tr class="student_data">
              <td><%= student.first_name %></td>
              <td><%= student.email %></td>
              <td><%= student.birthdate.present? ? format_date(student.birthdate) : 'N/A' %></td>
              <td><%= student.contact_no %></td>  
              <td><%= formatted_address(student) %></td>
              <td><%= link_to 'View', student_path(student), class: 'btn btn-info btn-sm' %></td>
              <td><%= link_to 'Edit', edit_student_path(student), class: 'btn btn-warning btn-sm' %></td>
              <td><%= button_to 'Delete', student_path(student), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure you want to delete this student?' } %></td>
            </tr>
          <% end %>
        </tbody>
        
    </div>
    </table>
  </div>
  <!-- <%= form_with url: students_path, local: true, multipart: true do |form| %>
  <div class="form-group">
    <%= form.label :csv_file, "Upload CSV File" %>
    <%= form.file_field :csv_file, class: "form-control" %>
  </div>
  <%= form.submit "Upload", class: "btn btn-primary" %>
<% end %> -->